Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
engine = create_engine(
    "heavydb://admin:HyperInteractive@localhost:6274/heavyai?protocol=binary"
)

con = engine.connect()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTTransportException[0m                       Traceback (most recent call last)
File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/heavydb/connection.py:268[0m, in [0;36mConnection.__init__[0;34m(self, uri, user, password, host, port, dbname, protocol, sessionid, bin_cert_validate, bin_ca_certs, idpurl, idpformusernamefield, idpformpasswordfield, idpsslverify)[0m
[1;32m    267[0m [38;5;28;01mtry[39;00m:
[0;32m--> 268[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_transport[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43m)[49m
[1;32m    269[0m [38;5;28;01mexcept[39;00m TTransportException [38;5;28;01mas[39;00m e:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/thrift/transport/TTransport.py:155[0m, in [0;36mTBufferedTransport.open[0;34m(self)[0m
[1;32m    154[0m [38;5;28;01mdef[39;00m [38;5;21mopen[39m([38;5;28mself[39m):
[0;32m--> 155[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__trans[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/thrift/transport/TSocket.py:146[0m, in [0;36mTSocket.open[0;34m(self)[0m
[1;32m    145[0m logger[38;5;241m.[39merror(msg)
[0;32m--> 146[0m [38;5;28;01mraise[39;00m TTransportException([38;5;28mtype[39m[38;5;241m=[39mTTransportException[38;5;241m.[39mNOT_OPEN, message[38;5;241m=[39mmsg)

[0;31mTTransportException[0m: Could not connect to any of [('::1', 6274, 0, 0), ('127.0.0.1', 6274)]

The above exception was the direct cause of the following exception:

[0;31mOperationalError[0m                          Traceback (most recent call last)
File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3280[0m, in [0;36mEngine._wrap_pool_connect[0;34m(self, fn, connection)[0m
[1;32m   3279[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3280[0m     [38;5;28;01mreturn[39;00m [43mfn[49m[43m([49m[43m)[49m
[1;32m   3281[0m [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mdbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m e:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:310[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    303[0m [38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    304[0m 
[1;32m    305[0m [38;5;124;03mThe connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    308[0m 
[1;32m    309[0m [38;5;124;03m"""[39;00m
[0;32m--> 310[0m [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:868[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m    867[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m--> 868[0m     fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m    870[0m     fairy[38;5;241m.[39m_pool [38;5;241m=[39m pool

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:476[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    474[0m [38;5;129m@classmethod[39m
[1;32m    475[0m [38;5;28;01mdef[39;00m [38;5;21mcheckout[39m([38;5;28mcls[39m, pool):
[0;32m--> 476[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    477[0m     [38;5;28;01mtry[39;00m:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:145[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    144[0m [38;5;28;01mexcept[39;00m:
[0;32m--> 145[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    146[0m         [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m     69[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mwarn_only:
[0;32m---> 70[0m         [43mcompat[49m[38;5;241;43m.[39;49m[43mraise_[49m[43m([49m
[1;32m     71[0m [43m            [49m[43mexc_value[49m[43m,[49m
[1;32m     72[0m [43m            [49m[43mwith_traceback[49m[38;5;241;43m=[39;49m[43mexc_tb[49m[43m,[49m
[1;32m     73[0m [43m        [49m[43m)[49m
[1;32m     74[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/compat.py:207[0m, in [0;36mraise_[0;34m(***failed resolving arguments***)[0m
[1;32m    206[0m [38;5;28;01mtry[39;00m:
[0;32m--> 207[0m     [38;5;28;01mraise[39;00m exception
[1;32m    208[0m [38;5;28;01mfinally[39;00m:
[1;32m    209[0m     [38;5;66;03m# credit to[39;00m
[1;32m    210[0m     [38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/[39;00m
[1;32m    211[0m     [38;5;66;03m# as the __traceback__ object creates a cycle[39;00m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:143[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    142[0m [38;5;28;01mtry[39;00m:
[0;32m--> 143[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    144[0m [38;5;28;01mexcept[39;00m:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:256[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    254[0m [38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 256[0m [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:371[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    370[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 371[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    372[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:665[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    664[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 665[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    666[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m     69[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mwarn_only:
[0;32m---> 70[0m         [43mcompat[49m[38;5;241;43m.[39;49m[43mraise_[49m[43m([49m
[1;32m     71[0m [43m            [49m[43mexc_value[49m[43m,[49m
[1;32m     72[0m [43m            [49m[43mwith_traceback[49m[38;5;241;43m=[39;49m[43mexc_tb[49m[43m,[49m
[1;32m     73[0m [43m        [49m[43m)[49m
[1;32m     74[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/compat.py:207[0m, in [0;36mraise_[0;34m(***failed resolving arguments***)[0m
[1;32m    206[0m [38;5;28;01mtry[39;00m:
[0;32m--> 207[0m     [38;5;28;01mraise[39;00m exception
[1;32m    208[0m [38;5;28;01mfinally[39;00m:
[1;32m    209[0m     [38;5;66;03m# credit to[39;00m
[1;32m    210[0m     [38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/[39;00m
[1;32m    211[0m     [38;5;66;03m# as the __traceback__ object creates a cycle[39;00m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:661[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    660[0m [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 661[0m [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    662[0m pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/create.py:590[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    589[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 590[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/default.py:597[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    595[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    596[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 597[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/heavyai/connection.py:725[0m, in [0;36mconnect[0;34m(uri, user, password, host, port, dbname, protocol, sessionid, bin_cert_validate, bin_ca_certs, idpurl, idpformusernamefield, idpformpasswordfield, idpsslverify)[0m
[1;32m    674[0m [38;5;124;03m"""[39;00m
[1;32m    675[0m [38;5;124;03mCreate a new Connection.[39;00m
[1;32m    676[0m 
[0;32m   (...)[0m
[1;32m    723[0m 
[1;32m    724[0m [38;5;124;03m"""[39;00m
[0;32m--> 725[0m [38;5;28;01mreturn[39;00m [43mConnection[49m[43m([49m
[1;32m    726[0m [43m    [49m[43muri[49m[38;5;241;43m=[39;49m[43muri[49m[43m,[49m
[1;32m    727[0m [43m    [49m[43muser[49m[38;5;241;43m=[39;49m[43muser[49m[43m,[49m
[1;32m    728[0m [43m    [49m[43mpassword[49m[38;5;241;43m=[39;49m[43mpassword[49m[43m,[49m
[1;32m    729[0m [43m    [49m[43mhost[49m[38;5;241;43m=[39;49m[43mhost[49m[43m,[49m
[1;32m    730[0m [43m    [49m[43mport[49m[38;5;241;43m=[39;49m[43mport[49m[43m,[49m
[1;32m    731[0m [43m    [49m[43mdbname[49m[38;5;241;43m=[39;49m[43mdbname[49m[43m,[49m
[1;32m    732[0m [43m    [49m[43mprotocol[49m[38;5;241;43m=[39;49m[43mprotocol[49m[43m,[49m
[1;32m    733[0m [43m    [49m[43msessionid[49m[38;5;241;43m=[39;49m[43msessionid[49m[43m,[49m
[1;32m    734[0m [43m    [49m[43mbin_cert_validate[49m[38;5;241;43m=[39;49m[43mbin_cert_validate[49m[43m,[49m
[1;32m    735[0m [43m    [49m[43mbin_ca_certs[49m[38;5;241;43m=[39;49m[43mbin_ca_certs[49m[43m,[49m
[1;32m    736[0m [43m    [49m[43midpurl[49m[38;5;241;43m=[39;49m[43midpurl[49m[43m,[49m
[1;32m    737[0m [43m    [49m[43midpformusernamefield[49m[38;5;241;43m=[39;49m[43midpformusernamefield[49m[43m,[49m
[1;32m    738[0m [43m    [49m[43midpformpasswordfield[49m[38;5;241;43m=[39;49m[43midpformpasswordfield[49m[43m,[49m
[1;32m    739[0m [43m    [49m[43midpsslverify[49m[38;5;241;43m=[39;49m[43midpsslverify[49m[43m,[49m
[1;32m    740[0m [43m[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/heavydb/connection.py:272[0m, in [0;36mConnection.__init__[0;34m(self, uri, user, password, host, port, dbname, protocol, sessionid, bin_cert_validate, bin_ca_certs, idpurl, idpformusernamefield, idpformpasswordfield, idpsslverify)[0m
[1;32m    271[0m     err [38;5;241m=[39m OperationalError([38;5;124m"[39m[38;5;124mCould not connect to database[39m[38;5;124m"[39m)
[0;32m--> 272[0m     [38;5;28;01mraise[39;00m err [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m    273[0m [38;5;28;01melse[39;00m:

[0;31mOperationalError[0m: Could not connect to database

The above exception was the direct cause of the following exception:

[0;31mOperationalError[0m                          Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      1[0m engine [38;5;241m=[39m create_engine(
[1;32m      2[0m     [38;5;124m"[39m[38;5;124mheavydb://admin:HyperInteractive@localhost:6274/heavyai?protocol=binary[39m[38;5;124m"[39m
[1;32m      3[0m )
[0;32m----> 5[0m con [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3234[0m, in [0;36mEngine.connect[0;34m(self, close_with_result)[0m
[1;32m   3219[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, close_with_result[38;5;241m=[39m[38;5;28;01mFalse[39;00m):
[1;32m   3220[0m     [38;5;124;03m"""Return a new :class:`_engine.Connection` object.[39;00m
[1;32m   3221[0m 
[1;32m   3222[0m [38;5;124;03m    The :class:`_engine.Connection` object is a facade that uses a DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3231[0m 
[1;32m   3232[0m [38;5;124;03m    """[39;00m
[0;32m-> 3234[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connection_cls[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mclose_with_result[49m[38;5;241;43m=[39;49m[43mclose_with_result[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/base.py:96[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events, _allow_revalidate)[0m
[1;32m     91[0m     [38;5;28mself[39m[38;5;241m.[39m_has_events [38;5;241m=[39m _branch_from[38;5;241m.[39m_has_events
[1;32m     92[0m [38;5;28;01melse[39;00m:
[1;32m     93[0m     [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m (
[1;32m     94[0m         connection
[1;32m     95[0m         [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m---> 96[0m         [38;5;28;01melse[39;00m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[1;32m     97[0m     )
[1;32m     99[0m     [38;5;28mself[39m[38;5;241m.[39m_transaction [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_nested_transaction [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    100[0m     [38;5;28mself[39m[38;5;241m.[39m__savepoint_seq [38;5;241m=[39m [38;5;241m0[39m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3313[0m, in [0;36mEngine.raw_connection[0;34m(self, _connection)[0m
[1;32m   3291[0m [38;5;28;01mdef[39;00m [38;5;21mraw_connection[39m([38;5;28mself[39m, _connection[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m   3292[0m     [38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[1;32m   3293[0m 
[1;32m   3294[0m [38;5;124;03m    The returned object is a proxied version of the DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3311[0m 
[1;32m   3312[0m [38;5;124;03m    """[39;00m
[0;32m-> 3313[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_wrap_pool_connect[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m,[49m[43m [49m[43m_connection[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3283[0m, in [0;36mEngine._wrap_pool_connect[0;34m(self, fn, connection)[0m
[1;32m   3281[0m [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mdbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m e:
[1;32m   3282[0m     [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m-> 3283[0m         [43mConnection[49m[38;5;241;43m.[39;49m[43m_handle_dbapi_exception_noconnection[49m[43m([49m
[1;32m   3284[0m [43m            [49m[43me[49m[43m,[49m[43m [49m[43mdialect[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m
[1;32m   3285[0m [43m        [49m[43m)[49m
[1;32m   3286[0m     [38;5;28;01melse[39;00m:
[1;32m   3287[0m         util[38;5;241m.[39mraise_(
[1;32m   3288[0m             sys[38;5;241m.[39mexc_info()[[38;5;241m1[39m], with_traceback[38;5;241m=[39msys[38;5;241m.[39mexc_info()[[38;5;241m2[39m]
[1;32m   3289[0m         )

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/base.py:2117[0m, in [0;36mConnection._handle_dbapi_exception_noconnection[0;34m(cls, e, dialect, engine)[0m
[1;32m   2115[0m     util[38;5;241m.[39mraise_(newraise, with_traceback[38;5;241m=[39mexc_info[[38;5;241m2[39m], from_[38;5;241m=[39me)
[1;32m   2116[0m [38;5;28;01melif[39;00m should_wrap:
[0;32m-> 2117[0m     [43mutil[49m[38;5;241;43m.[39;49m[43mraise_[49m[43m([49m
[1;32m   2118[0m [43m        [49m[43msqlalchemy_exception[49m[43m,[49m[43m [49m[43mwith_traceback[49m[38;5;241;43m=[39;49m[43mexc_info[49m[43m[[49m[38;5;241;43m2[39;49m[43m][49m[43m,[49m[43m [49m[43mfrom_[49m[38;5;241;43m=[39;49m[43me[49m
[1;32m   2119[0m [43m    [49m[43m)[49m
[1;32m   2120[0m [38;5;28;01melse[39;00m:
[1;32m   2121[0m     util[38;5;241m.[39mraise_(exc_info[[38;5;241m1[39m], with_traceback[38;5;241m=[39mexc_info[[38;5;241m2[39m])

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/compat.py:207[0m, in [0;36mraise_[0;34m(***failed resolving arguments***)[0m
[1;32m    204[0m     exception[38;5;241m.[39m__cause__ [38;5;241m=[39m replace_context
[1;32m    206[0m [38;5;28;01mtry[39;00m:
[0;32m--> 207[0m     [38;5;28;01mraise[39;00m exception
[1;32m    208[0m [38;5;28;01mfinally[39;00m:
[1;32m    209[0m     [38;5;66;03m# credit to[39;00m
[1;32m    210[0m     [38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/[39;00m
[1;32m    211[0m     [38;5;66;03m# as the __traceback__ object creates a cycle[39;00m
[1;32m    212[0m     [38;5;28;01mdel[39;00m exception, replace_context, from_, with_traceback

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3280[0m, in [0;36mEngine._wrap_pool_connect[0;34m(self, fn, connection)[0m
[1;32m   3278[0m dialect [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mdialect
[1;32m   3279[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3280[0m     [38;5;28;01mreturn[39;00m [43mfn[49m[43m([49m[43m)[49m
[1;32m   3281[0m [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mdbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m e:
[1;32m   3282[0m     [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:310[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    302[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m):
[1;32m    303[0m     [38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    304[0m 
[1;32m    305[0m [38;5;124;03m    The connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    308[0m 
[1;32m    309[0m [38;5;124;03m    """[39;00m
[0;32m--> 310[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:868[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m    865[0m [38;5;129m@classmethod[39m
[1;32m    866[0m [38;5;28;01mdef[39;00m [38;5;21m_checkout[39m([38;5;28mcls[39m, pool, threadconns[38;5;241m=[39m[38;5;28;01mNone[39;00m, fairy[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m    867[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m--> 868[0m         fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m    870[0m         fairy[38;5;241m.[39m_pool [38;5;241m=[39m pool
[1;32m    871[0m         fairy[38;5;241m.[39m_counter [38;5;241m=[39m [38;5;241m0[39m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:476[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    474[0m [38;5;129m@classmethod[39m
[1;32m    475[0m [38;5;28;01mdef[39;00m [38;5;21mcheckout[39m([38;5;28mcls[39m, pool):
[0;32m--> 476[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    477[0m     [38;5;28;01mtry[39;00m:
[1;32m    478[0m         dbapi_connection [38;5;241m=[39m rec[38;5;241m.[39mget_connection()

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:145[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    143[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[1;32m    144[0m     [38;5;28;01mexcept[39;00m:
[0;32m--> 145[0m         [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    146[0m             [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()
[1;32m    147[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m     68[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[1;32m     69[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mwarn_only:
[0;32m---> 70[0m         [43mcompat[49m[38;5;241;43m.[39;49m[43mraise_[49m[43m([49m
[1;32m     71[0m [43m            [49m[43mexc_value[49m[43m,[49m
[1;32m     72[0m [43m            [49m[43mwith_traceback[49m[38;5;241;43m=[39;49m[43mexc_tb[49m[43m,[49m
[1;32m     73[0m [43m        [49m[43m)[49m
[1;32m     74[0m [38;5;28;01melse[39;00m:
[1;32m     75[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m compat[38;5;241m.[39mpy3k [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_exc_info[[38;5;241m1[39m]:
[1;32m     76[0m         [38;5;66;03m# emulate Py3K's behavior of telling us when an exception[39;00m
[1;32m     77[0m         [38;5;66;03m# occurs in an exception handler.[39;00m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/compat.py:207[0m, in [0;36mraise_[0;34m(***failed resolving arguments***)[0m
[1;32m    204[0m     exception[38;5;241m.[39m__cause__ [38;5;241m=[39m replace_context
[1;32m    206[0m [38;5;28;01mtry[39;00m:
[0;32m--> 207[0m     [38;5;28;01mraise[39;00m exception
[1;32m    208[0m [38;5;28;01mfinally[39;00m:
[1;32m    209[0m     [38;5;66;03m# credit to[39;00m
[1;32m    210[0m     [38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/[39;00m
[1;32m    211[0m     [38;5;66;03m# as the __traceback__ object creates a cycle[39;00m
[1;32m    212[0m     [38;5;28;01mdel[39;00m exception, replace_context, from_, with_traceback

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:143[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    141[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_inc_overflow():
[1;32m    142[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 143[0m         [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    144[0m     [38;5;28;01mexcept[39;00m:
[1;32m    145[0m         [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:256[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    253[0m [38;5;28;01mdef[39;00m [38;5;21m_create_connection[39m([38;5;28mself[39m):
[1;32m    254[0m     [38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 256[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:371[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    369[0m [38;5;28mself[39m[38;5;241m.[39m__pool [38;5;241m=[39m pool
[1;32m    370[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 371[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    372[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:665[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    663[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    664[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 665[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    666[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)
[1;32m    667[0m [38;5;28;01melse[39;00m:
[1;32m    668[0m     [38;5;66;03m# in SQLAlchemy 1.4 the first_connect event is not used by[39;00m
[1;32m    669[0m     [38;5;66;03m# the engine, so this will usually not be set[39;00m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m     68[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[1;32m     69[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mwarn_only:
[0;32m---> 70[0m         [43mcompat[49m[38;5;241;43m.[39;49m[43mraise_[49m[43m([49m
[1;32m     71[0m [43m            [49m[43mexc_value[49m[43m,[49m
[1;32m     72[0m [43m            [49m[43mwith_traceback[49m[38;5;241;43m=[39;49m[43mexc_tb[49m[43m,[49m
[1;32m     73[0m [43m        [49m[43m)[49m
[1;32m     74[0m [38;5;28;01melse[39;00m:
[1;32m     75[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m compat[38;5;241m.[39mpy3k [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_exc_info[[38;5;241m1[39m]:
[1;32m     76[0m         [38;5;66;03m# emulate Py3K's behavior of telling us when an exception[39;00m
[1;32m     77[0m         [38;5;66;03m# occurs in an exception handler.[39;00m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/util/compat.py:207[0m, in [0;36mraise_[0;34m(***failed resolving arguments***)[0m
[1;32m    204[0m     exception[38;5;241m.[39m__cause__ [38;5;241m=[39m replace_context
[1;32m    206[0m [38;5;28;01mtry[39;00m:
[0;32m--> 207[0m     [38;5;28;01mraise[39;00m exception
[1;32m    208[0m [38;5;28;01mfinally[39;00m:
[1;32m    209[0m     [38;5;66;03m# credit to[39;00m
[1;32m    210[0m     [38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/[39;00m
[1;32m    211[0m     [38;5;66;03m# as the __traceback__ object creates a cycle[39;00m
[1;32m    212[0m     [38;5;28;01mdel[39;00m exception, replace_context, from_, with_traceback

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/pool/base.py:661[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    659[0m [38;5;28;01mtry[39;00m:
[1;32m    660[0m     [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 661[0m     [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    662[0m     pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)
[1;32m    663[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/create.py:590[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    588[0m         [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    589[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 590[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/sqlalchemy/engine/default.py:597[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    595[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    596[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 597[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/heavyai/connection.py:725[0m, in [0;36mconnect[0;34m(uri, user, password, host, port, dbname, protocol, sessionid, bin_cert_validate, bin_ca_certs, idpurl, idpformusernamefield, idpformpasswordfield, idpsslverify)[0m
[1;32m    658[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m(
[1;32m    659[0m     uri[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    660[0m     user[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m    672[0m     idpsslverify[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m    673[0m ):
[1;32m    674[0m     [38;5;124;03m"""[39;00m
[1;32m    675[0m [38;5;124;03m    Create a new Connection.[39;00m
[1;32m    676[0m 
[0;32m   (...)[0m
[1;32m    723[0m 
[1;32m    724[0m [38;5;124;03m    """[39;00m
[0;32m--> 725[0m     [38;5;28;01mreturn[39;00m [43mConnection[49m[43m([49m
[1;32m    726[0m [43m        [49m[43muri[49m[38;5;241;43m=[39;49m[43muri[49m[43m,[49m
[1;32m    727[0m [43m        [49m[43muser[49m[38;5;241;43m=[39;49m[43muser[49m[43m,[49m
[1;32m    728[0m [43m        [49m[43mpassword[49m[38;5;241;43m=[39;49m[43mpassword[49m[43m,[49m
[1;32m    729[0m [43m        [49m[43mhost[49m[38;5;241;43m=[39;49m[43mhost[49m[43m,[49m
[1;32m    730[0m [43m        [49m[43mport[49m[38;5;241;43m=[39;49m[43mport[49m[43m,[49m
[1;32m    731[0m [43m        [49m[43mdbname[49m[38;5;241;43m=[39;49m[43mdbname[49m[43m,[49m
[1;32m    732[0m [43m        [49m[43mprotocol[49m[38;5;241;43m=[39;49m[43mprotocol[49m[43m,[49m
[1;32m    733[0m [43m        [49m[43msessionid[49m[38;5;241;43m=[39;49m[43msessionid[49m[43m,[49m
[1;32m    734[0m [43m        [49m[43mbin_cert_validate[49m[38;5;241;43m=[39;49m[43mbin_cert_validate[49m[43m,[49m
[1;32m    735[0m [43m        [49m[43mbin_ca_certs[49m[38;5;241;43m=[39;49m[43mbin_ca_certs[49m[43m,[49m
[1;32m    736[0m [43m        [49m[43midpurl[49m[38;5;241;43m=[39;49m[43midpurl[49m[43m,[49m
[1;32m    737[0m [43m        [49m[43midpformusernamefield[49m[38;5;241;43m=[39;49m[43midpformusernamefield[49m[43m,[49m
[1;32m    738[0m [43m        [49m[43midpformpasswordfield[49m[38;5;241;43m=[39;49m[43midpformpasswordfield[49m[43m,[49m
[1;32m    739[0m [43m        [49m[43midpsslverify[49m[38;5;241;43m=[39;49m[43midpsslverify[49m[43m,[49m
[1;32m    740[0m [43m    [49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/sqla-heavyai/lib/python3.10/site-packages/heavydb/connection.py:272[0m, in [0;36mConnection.__init__[0;34m(self, uri, user, password, host, port, dbname, protocol, sessionid, bin_cert_validate, bin_ca_certs, idpurl, idpformusernamefield, idpformpasswordfield, idpsslverify)[0m
[1;32m    270[0m [38;5;28;01mif[39;00m e[38;5;241m.[39mNOT_OPEN:
[1;32m    271[0m     err [38;5;241m=[39m OperationalError([38;5;124m"[39m[38;5;124mCould not connect to database[39m[38;5;124m"[39m)
[0;32m--> 272[0m     [38;5;28;01mraise[39;00m err [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m    273[0m [38;5;28;01melse[39;00m:
[1;32m    274[0m     [38;5;28;01mraise[39;00m

[0;31mOperationalError[0m: (heavydb.exceptions.OperationalError) Could not connect to database
(Background on this error at: https://sqlalche.me/e/14/e3q8)
OperationalError: (heavydb.exceptions.OperationalError) Could not connect to database
(Background on this error at: https://sqlalche.me/e/14/e3q8)

